### PR TITLE
feat(octez): bump octez  to v20

### PR DESCRIPTION
**Pull request by alanmarkoTrilitech**
# Context
https://app.asana.com/0/1205770721173533/1207404145514422

# Description
This PR updates octez to v20 and protocol version to Paris, so that we can run jstz on ghostnet. 

# Manually testing the PR
run sandbox and deploy a smart function

### CODE REVIEW

**Comment by johnyob** [comment]
Seems like the sandbox is broken for me 😔 The kernel fails to parse the external message sent by the jstz CLI

**Comment by alanmarkoTrilitech** [comment]
> Seems like the sandbox is broken for me 😔 The kernel fails to parse the external message sent by the jstz CLI

I haven't encountered this issue. Have you done make build and updated config.json?

**Comment by alanmarkoTrilitech** [comment]
you need to checkout tezos to octez-v20.0

**Comment by johnyob** [comment]
> you need to checkout tezos to octez-v20.0
> I haven't encountered this issue. Have you done make build and updated config.json?

I did both of these. Nuking my Rust build cache seems to have done the trick --- though I'm not too sure why 🤷

**Review by johnyob — APPROVED** [review]

**Pull request merged**
