### PR TITLE
Git: Setup templates

### PR DESCRIPTION
**Pull request by Laucans**
# Context
To setup project [Runtime-API](https://github.com/orgs/trilitech/projects/5/views/1) we need templates

# Description
Theses template will be used for issues creation and PR

### CODE REVIEW

**Comment by johnyob** [comment]
Just checking: the introduction of `PULL_REQUEST_TEMPLATE` doesn't affect our current template `pull_request_template.md`?

**Comment by Laucans** [comment]
> Just checking: the introduction of `PULL_REQUEST_TEMPLATE` doesn't affect our current template `pull_request_template.md`?

Maybe we can just move it into PULL_REQUEST_TEMPLATE and name it ? Which name do you want ?

**Comment by johnyob** [comment]
> Maybe we can just move it into PULL_REQUEST_TEMPLATE and name it ? Which name do you want ?

'Default'?

**Comment by johnyob** [comment]
Also added a commit that fixes some nit-picks: https://github.com/trilitech/jstz/pull/88/commits/e8427d9c64009c8cb8e5da2e13fb6f789e0166e6

**Comment by Laucans** [comment]
So should be good now

**Review by johnyob — APPROVED** [review]

**Pull request merged**
