### PR TITLE
feat(cli): improve logging for commands

### PR DESCRIPTION
**Pull request by johnyob**
# Context

# Description

**Dependencies**: #361 

 This PR adds debug logging and improves the overall log output of the CLI. Logging levels can be configured 
 using the `JSTZ_LOG` environment variable.
    
All debug logs for commands should contain:
- The command and all flags / positional arguments
- The config on load and save, additionally the config file contents for debugging deserialization errors
- Any additional command-specific logs

# Manually testing the PR

### CODE REVIEW

**Review by alanmarkoTrilitech — CHANGES_REQUESTED** [review]
I see that the other PR was merged to this despite my comments. Please check the comments on the emoji PR.

**Comment by johnyob** [comment]
> I see that the other PR was merged to this despite my comments. Please check the comments on the emoji PR.

Reverted -- will open a new PR for any additional discussions for the CLI emojis

**Review by alanmarkoTrilitech — COMMENTED** [review]
Seems good to me, but I'm just getting Your configuration file is improperly configured..

What is the correct ocnfig?

**Comment by johnyob** [comment]
> What is the correct config?

```
{
  "octez_path": "/Users/ajob410/tezos/jstz",
  "sandbox": null,
  "current_alias": null,
  "accounts": {}
}
```

**Review by alanmarkoTrilitech — APPROVED** [review]
LGTM, I would change some minor things in the formatting of what it is printing but that can be left for further PRs later.

**Pull request merged**
