### PR TITLE
feat(cli): add `completions` command to jstz

### PR DESCRIPTION
**Pull request by johnyob**
# Context

**Related Tasks**: [Shell autocompletions for CLI](https://app.asana.com/0/1205770721173531/1206472793750873/f)

# Description

This PR adds a `completions` command to `jstz`, which prints the autocompletions for the CLI to stdout

# Manually testing the PR

Since we don't yet globally install jstz as a binary, it's a bit finicky to test locally. 

For zsh:
```sh
autoload -U compinit && compinit
source <(cargo run --bin jstz -- completions --shell=zsh)
compdef _jstz ./target/debug/jstz
```

To use the completions, you must use `./target/debug/jstz [Tab]` ([Tab] denotes you pressing tab). I've not been able to get this to work with `cargo run --bin jstz -- ...`

For other shells:
https://github.com/clap-rs/clap/issues/2488#issuecomment-864576617

### CODE REVIEW

**Review by sam-finch-tezos — APPROVED** [review]
🎉  🥳 Awesome!
Happy to merge on the grounds that merged is better than not merged.
I had to install a couple of things to get it to work
```bash
brew install --cask autodmg
brew install compiledb
```

Could I suggest the following additions (if possible) before you close the ticket
* Add whatever is necessary to our `nix` to work in the `nix-shell`
* Add something to the makefile so that `target/debug/jstz` and `target/release/jstz` are set up for you.

If that's not possible or a pain to do then don't worry

**Comment by johnyob** [comment]
>Add whatever is necessary to our nix to work in the nix-shell

If you're using direnv (as you ought to be), then the shell is configured externally to nix

> Add something to the makefile so that target/debug/jstz and target/release/jstz are set up for you.

This is possible, I can probably set it up for zsh. But perhaps in a different PR?

**Comment by sam-finch-tezos** [comment]
> > Add something to the makefile so that target/debug/jstz and target/release/jstz are set up for you.
> 
> This is possible, I can probably set it up for zsh. But perhaps in a different PR?
Absolutely, just add a note to the ticket and but it back into planned.

**Comment by johnyob** [comment]
> Absolutely, just add a note to the ticket and but it back into planned.

https://app.asana.com/0/1205770721173531/1206520076651987/f

**Pull request merged**
